#cloud-config

# Install .Net Runtime 8.0
runcmd:
  # Register Microsoft repository (which includes .Net Runtime 9.0 package)
    - add-apt-repository ppa:dotnet/backports -y
    - apt-get update
    - apt-get install -y aspnetcore-runtime-9.0

# Create a service for the application
write_files:
  - path: /etc/systemd/system/GithubActionsDemo.service
    content: |
      [Unit]
      Description=ASP.NET Web App running on Ubuntu

      [Service]
      WorkingDirectory=/opt/GithubActionsDemo
      ExecStart=/usr/bin/dotnet /opt/GithubActionsDemo/GithubActionsDemo.dll
      Restart=always
      RestartSec=10
      KillSignal=SIGINT
      SyslogIdentifier=GithubActionsDemo
      User=www-data
      Environment=ASPNETCORE_ENVIRONMENT=Production
      Environment=DOTNET_PRINT_TELEMETRY_MESSAGE=false
      Environment="ASPNETCORE_URLS=http://*:5000"

      [Install]
      WantedBy=multi-user.target
    owner: root:root
    permissions: '0644'

systemd:
  units:
    - name: GithubActionsDemo.service
      enabled: true